source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets = ['Alamofire','AlamofireObjectMapper']
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end

use_frameworks!

target ‘SwiftStudy1’ do
    #网络请求
    pod 'Alamofire', '~> 4.6.0'
    #网络请求转对象
    pod 'AlamofireObjectMapper', '~> 5.0.0'
    #masonry约束swift版
    pod 'SnapKit', '~> 4.0.0'
    
    pod 'HandyJSON'
    
    pod 'SwiftyJSON'
end
